version: '3'

services:
  cassandra:
    build:
      context: docker/cassandra
    ports:
      - "${CASSANDRA_IP_PORT:-127.0.0.1:9042}:9042"
    environment:
      MAX_HEAP_SIZE: ${CASSANDRA_MAX_HEAP_SIZE:-256M}
      HEAP_NEWSIZE: ${CASSANDRA_HEAP_NEWSIZE:-128M}
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 3s
      timeout: 2s
      retries: 60
